### ISSUE TITLE
Review Sam's GitHub ways of working draft

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#104]
Please read through Sam's draft and add questions, comments, or changes as necessary.

The file is here: [GitHub ways of working.docx](https://defra.sharepoint.com/:w:/s/MST-Defra-EAU-Spatial-Data-Science/EZ01eejz6OxNs2UiqxY2TIoBYEMFoBdxnv398_EoE3NVzg?e=5lsah1)

**Comment by TimAshelford** [comment]
@s-flint-defra Looks good to me. Very clear and will be a great resource for somebody new to the Project and this way of working.  I've added a couple of comments, no show stoppers!

**Comment by lara56** [comment]
@s-flint-defra I really like it, very comprehensive and easy to read. I've just added a few questions/ comments where it wasn't immediately clear to me, but could also be because I wasn't reading it properly, so feel free to ignore!

**Comment by jpd-defra** [comment]
@s-flint-defra - nice work Sam, it's great to get the results of some of our sprint chats down on paper. I have added some suggestions for a few extra sub-headed sections to help give a bit more context, and also suggest a glossary- where terms such as reprex, moscow and other project management/code-related terms can be described.

**Comment by danlewis85** [comment]
This is excellent @s-flint-defra. I think there are two things that we should add:
1. Why, when and how to comment on an issue.
2. Now that we have 'epics', what is a epic and how does it relate to an issue.

Both of these could be future issues to raise against an established version though.

**Comment by s-flint-defra** [comment]
Closing as this task is complete and features in the knowledge hub.
