### ISSUE TITLE
Appending metadata to xarray Dataset/DataArray - inconsistent behaviour

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#109]
It appears that `TiledVectorLayer.to_dataset_as_raster`, when provided with metadata, appends the metadata as xarray Attributes to the xarray Dataset. 

Whereas `TiledVectorLayer.to_data_array_as_mask` seems to append metadata as xarray Attributes to the xarray DataArray. 

This probably isn't a big issue, although it would be nice to have harmonised behaviour across all rasterisation functions.

**Comment by s-flint-defra** [comment]
@jpd-defra I believe TiledVecctorLayer has been superseded - makes this issue irrelevant unless there is still inconsistent behaviour in the latest version?

**Comment by jpd-defra** [comment]
> @jpd-defra I believe TiledVecctorLayer has been superseded - makes this issue irrelevant unless there is still inconsistent behaviour in the latest version?

Agreed, this should no longer be an issue. Closing.
