### ISSUE TITLE
Addressing linting issues raised by `flake8`

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#113]
This is now failing because `flake8` is finding issues, not because `flake8` itself is failing.

_Originally posted by @EFT-Defra in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/issues/112#issuecomment-1233126363_

**Comment by s-flint-defra** [comment]
This issue references #112 which has an approved PR associated with it. Closing.
