### ISSUE TITLE
Provisional classification of transforms

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#129]

**Comment by alistairedwardes-eau** [comment]
@EFT-Defra 

These are some initial thoughts. I might have over-emphasised transformations that are essentially data cleaning, whereas the main purpose I think here is more around harmonising data to a common data model schema.  

**Syntax and structure**
_Describe transformation to clean data and bring it to a consistent format._
 
- Data type conversions
  - Character set reencoding
  - Data type coercion e.g. integers from strings
  - Date-time conversion
  - Precision rounding
- Formatting
  - Date formatting
  - Splitting / extracting variables from strings
  - Recoding categories
  - Renaming variables
- Cleaning
  - Imputing missing values
  - Filtering records (e.g. NAs and missing values)
  - Recoding NAs e.g. as 0
  - Deduplicate records
  - Outlier detection
- Consistency
  - Linking e.g. by enforcing integrity constraints
- Data shape
  - Select variables
  - Pivot / fold / unfold
  - Flatten tree / nested data
  - Aggregation / group by
  	
**Semantics**
_Describe operations to transform the data semantics to a common data model._

- Schema transformation
  - Semantic mapping
  - Reclassification e.g. by value range
  - Coding (free text to categories)
  - Splitting and merging columns
  - Augment / expand e.g. country code to country
  - Filtering by values
  - Logical consistency validation
- Statistical
  - Derive / calculate variables
  - Calibration
  - Interpolate
  - Rescale
  - Normalise
  - Sample

**Geography**
_Describe transformation to (or using) the geographic elements of the data to bring it to a consistent state._

- Topological
  - Dimension reduction (e.g. poly -> centre line)
  - Surface interpolation (points to surface)
  - Extrusion 2d -> 3d
- Geometric
  - Geometry validation
  - Geometry flattening
  - Raster-vector conversion
  - Edge matching 
  - Generalisation / simplification / geometric manipulation
  - Reprojection
  - Densify
  - Coordinate rounding
  - Set operations
- Semantics
  - Spatial join
