### ISSUE TITLE
Create categorical column from more than one layer / create new categorical column from union of categorical columns

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#142]

**Comment by jamesgyoung** [comment]
@EFT-Defra is this still relevant? If it is what should this look like? There was a union function produced (not integrated into the data model though) but I'm not sure it was for this use case but I could be mistaken.

**Comment by EFT-Defra** [comment]
Hi @JamesKeny0n, I think that what I was imagining here is a situation where a dataset is split across multiple files or layers and so a categorical column cannot necessarily be created from a single file or layer because it may not contain all the possible values that exist in the full dataset.

I believe that this shouldn't be an issue anymore now that `categorize` is a standalone method as it can be run after the full dataset has been recreated from several files or layers.

Unless you can think of something I'm missing, I think this can be closed.

**Comment by jamesgyoung** [comment]
I agree.
