### ISSUE TITLE
Add indexing method to `DataFrameWrapper`

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#152]

**Comment by jpd-defra** [comment]
Implement Ed/Dan's indexing function as a standalone method in `DataFrameWrapper`

**Comment by jpd-defra** [comment]
Example in this notebook:

https://adb-7393756451346106.6.azuredatabricks.net/?o=7393756451346106#notebook/121189784893658/command/528826611801412

**Comment by EFT-Defra** [comment]
Closing issue as #153 is now on the board
