### ISSUE TITLE
Review pull requests

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#16]
- [x] #25
- [x] #26

**Comment by TimAshelford** [comment]
- [ ] review Dan's pull request

**Comment by EFT-Defra** [comment]
@TimAshelford, I've moved your comment to the main issue body so that I can then split the bullets out as tasks.

**Comment by TimAshelford** [comment]
@EFT-Defra thanks.

**Comment by s-flint-defra** [comment]
Given @EFT-Defra comment around moving the issues, I will assume this is captured elsewhere and close this issue.
