### ISSUE TITLE
Apply library to live use cases

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#17]
- [x] Defra-Data-Science-Centre-of-Excellence/sds-data-model#72
- [ ] Defra-Data-Science-Centre-of-Excellence/sds-asset-recipes#14

**Comment by s-flint-defra** [comment]
I think the open task in this issue RE agri productivity is captured in the asset baseline tasks, specifically Defra-Data-Science-Centre-of-Excellence/sds-asset-recipes#18. While it is not productivity specifically, that would be the next logical step using the WFM I am going to close this issue and create a new one from the open task.
