### ISSUE TITLE
Add aim of project and the expected functionality for 0.1. release to README

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#18]
Given that we want to test this library on live use cases (See #17), are we missing any essential functionality?

**Comment by EFT-Defra** [comment]
@jpd-defra, @PiumiA, is there anything we need for 30by30? 

@danlewis85, what about land use modelling?

@s-flint-defra , @JordanPinder-Defra, are we missing something that will prevent you from apply this to some subset of SP?

**Comment by jpd-defra** [comment]
RE: 30by30 - once we have strings working in the rasterization, that should be enough functionality to help us progress / demonstrate utility for now.

**Comment by TimAshelford** [comment]
Dan lead
