### ISSUE TITLE
geometry column name bug in _to_zarr_region

### ISSUE THREAD

**Issue by danlewis85** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#184]
The _to_zarr_region helper function contains the following code:
```
gpdf = GeoDataFrame(
        data=pdf,
        geometry=GeoSeries.from_wkb(pdf[geometry_column_name]),
        crs="EPSG:27700",
    )

    mask = geometry_mask(
        geometries=gpdf[geometry_column_name], # the issue is with this line <--
        out_shape=out_shape,
        transform=transform,
        invert=invert,
    ).astype(dtype)
```

The geometry_mask should take gpdf['geometry'] as if you're using a geometry_column_name other than 'geometry' it will fail as the defualt geometry column name for a geodataframe is geometry, nto necessarily geometry_column_name.

**Comment by danlewis85** [comment]
Issue is in this function: https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/188b5a5336edd666ef10d3e4e5aba1bd842ad753/src/sds_data_model/_dataframe.py#L172

**Comment by danlewis85** [comment]
I think the fix to the above will be:

```
gpdf = GeoDataFrame(
        data=pdf,
        geometry=GeoSeries.from_wkb(pdf[geometry_column_name]),
        crs="EPSG:27700",
    )
mask = geometry_mask(
        geometries=gpdf['geometry'], # <-- the fix is here 
        out_shape=out_shape,
        transform=transform,
        invert=invert,
    ).astype(dtype)
```

However, I haven't checked to make sure this doesn't create issues further on, so that'll be needed.

**Comment by jamesgyoung** [comment]
Although refactored a fix was merged:

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/4eccddb1f6499a6d7814486b0fd4b3f4509e19ab/src/sds_data_model/_dataframe.py#L616-L620
