### ISSUE TITLE
Ways of working: GitHub projects and pull requests

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#19]
- [ ] #75
- [x] #76

**Comment by EFT-Defra** [comment]
Separate task from review

- We remove the "In review" column from the board
- A task is "done" when a pull request is created
- When you trigger a pull request, you should also create a review task which will then be tracked across the board
- If a review results in a request for changes, those changes should be captured in a new task
- When that request for changes has been addressed, a new review task should be created
- Ad infinitum
