### ISSUE TITLE
Add support for reading from parquet

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#22]
It seems that [parquet](https://www.jumpingrivers.com/blog/parquet-file-format-big-data-r/) is becoming a favoured vector format, but it is not currently supported as a readable filetype for the vector functions in the data model.

Request to add support for reading from parquet to `VectorLayer` and `TiledVectorLayer` functions.

**Comment by jamesgyoung** [comment]
[`geopandas.read_parquet`](https://github.com/geopandas/geopandas/blob/5c8ae832e030228b5deec02588c4e1b78dee0f18/geopandas/io/arrow.py#L252-L301) does not support bbox reads as `geopandas.read_file` can.

Issue has already been raised: [ENH: Filter by bbox for read_parquet #2430](https://github.com/geopandas/geopandas/issues/2430)

**Comment by EFT-Defra** [comment]
Duplicate #106
