### ISSUE TITLE
Module-level docstrings

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#27]
> [...] It may be out of the scope of this PR, but some way of intergrating a purely generated example to demonstrate the new rasterization potential would be helpful. Is there a way to embed an example in the help/description of the function where a dummy dataset is generated from scratch, and put through the function to show the utility. Just an idea, so don't worry if it's not feasible.

_Originally posted by @jpd-defra in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/20#pullrequestreview-1018659076_

Module-level docstring may provide the end-user perspective on usage that James in asking for here. See, for example, the module-level docstring [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/pyspark-vector-files/blob/main/src/pyspark_vector_files/__init__.py).

**Comment by s-flint-defra** [comment]
Discussed with @jpd-defra - this is complete and available here https://defra-data-science-centre-of-excellence.github.io/sds-data-model/usage.html
