### ISSUE TITLE
`to_dataset_as_raster` not accepting string columns

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#28]
The `to_dataset_as_raster` function relies on `rasterio.dtypes.get_minimum_dtype` to work out minimum data type. However this function does not account for columns with strings and throws an error if provided with one.

@s-flint-defra suggests following datacube's approach of handling other datatypes.

**Comment by TimAshelford** [comment]
duplicate of  #33
