### ISSUE TITLE
Parse Gemini 2.3 metadata: "Mandatory", single-value elements

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#34]
- [x] Title
- [x] Abstract
- [x] Lineage
- [x] Metadata date
- [x] Metadata language
- [ ] Spatial data service type
- [x] Resource type
- [x] File Identifier

**Comment by PiumiA** [comment]
I can't seem to find any information regarding the spatial data service type in the Gemini documentation or find it in the metadata xml files I checked.
