### ISSUE TITLE
Explore `geocube` / how do deal with things that aren't Boolean masks?

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#4]
We need to be able to rasterise one or more attributes from a vector file. These attributes may be of any data type.

To successfully complete this epic, you will need to demonstrate the following:

- Convert a `TiledVectorLayer` into a [xarray Dataset](https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dataset) with [DataArray](https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dataarray)s representing at least two different attributes
- The DataArrays must be of different data types
- The DataArrays must match the dimension of the British National Grid, with resolution 10mx10m

**Comment by jamesgyoung** [comment]
- Familiarisation with rasterization protocols in geocube and rasterio. - How do they function? Benefits of each approach? - Decide on implementation of this feature (i.e. integrate geocube vs expand rasterio functionality)

#### [Geocube](https://github.com/corteva/geocube)
- The current output of the rasterization function is an xarray.Dataset(?) - Our library requires the function to return a delayed np.array/dask array - Extract the relevant functions from geocube for rasterization (if possible) and modify to implement our desired data types.
- Evaluate integration/usage of the coordinates geocube stores

#### [Rasterio](https://github.com/rasterio/rasterio)
- The current function allows for a singular data type (string) - Expand available datatypes

**Comment by EFT-Defra** [comment]
The library currently uses two rasterisation functions: `_get_mask`, which wraps `rasterio`'s `geometry_mask`, and `_to_categorical_raster`, which wraps `rasterio`'s `rasterize`.

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/f2769517b0531954e35de12b4db0bbee70cd38a9/src/sds_data_model/_vector.py#L73-L97

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/f2769517b0531954e35de12b4db0bbee70cd38a9/src/sds_data_model/_vector.py#L110-L135

These functions return `dask` [Delayed](https://docs.dask.org/en/stable/delayed.html) objects that are then converted into `dask` [Array](https://docs.dask.org/en/stable/array.html)s and passed to the xarray DataArray constructor.

To allow for arbitrary rasterisation, I think you'll need to refactor my code to either use `geocube` directly, use some of it's internal functions, or use some of it's code.
