### ISSUE TITLE
Geopandas error reading incomplete datetime strings

### ISSUE THREAD

**Issue by danlewis85** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#57]
This is an interesting error that I discovered when having to work with RPA land parcels data, I've created two examples that might actually point to this being a bug (of sorts) in `geopandas`, would be interested in diagnosis and then possibly raising as an issue on the geopandas github.

The land parcels data contains a number of datetime columns, if the datetime string is bad, it should return a NaT (not a time) value as in the example below:
```python
import geopandas
from shapely.geometry import Point
import tempfile

# Fully corrupt datetime

data = [[1, '1990-02-0300:00:00'],[2, '2002-08-2118:00:00'],[3, '2019-10-3019:00:05'],
        [4, '2008-02-2906:30:45'],[5, '9999-99-9900:00:00']]
geom = [Point(1,1),Point(2,2),Point(3,3),Point(4,4),Point(5,5)]

gdf = geopandas.GeoDataFrame(data = data, columns = ['uid', 'date'], crs = None, geometry=geom)

myschema = {'geometry': 'Point', 'properties': {'uid': 'int', 'date':'datetime'}}

with tempfile.TemporaryDirectory() as td:
    gdf.to_file(f"{td}/temp.gpkg", driver='GPKG', schema=myschema)
    
    print(geopandas.read_file(f"{td}/temp.gpkg"))
```
If you run the above, you should see the 5th row populated with NaT.

However, if you have a partially wrong datetime the behaviour is different, for instance:
```python
import geopandas
from shapely.geometry import Point
import tempfile

# Semi corrupt datetime

data = [[1, '1990-02-0300:00:00'],[2, '2002-08-2118:00:00'],[3, '2019-10-3019:00:05'],
        [4, '2008-02-2906:30:45'],[5, '9999-12-3100:00:00']]
geom = [Point(1,1),Point(2,2),Point(3,3),Point(4,4),Point(5,5)]

gdf = geopandas.GeoDataFrame(data = data, columns = ['uid', 'date'], crs = None, geometry=geom)

myschema = {'geometry': 'Point', 'properties': {'uid': 'int', 'date':'datetime'}}

with tempfile.TemporaryDirectory() as td:
    gdf.to_file(f"{td}/temp.gpkg", driver='GPKG', schema=myschema)
    
    print(geopandas.read_file(f"{td}/temp.gpkg"))
```
This returns the following error: `OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-12-31 00:00:00`

The source of the error is ultimately how geopandas handles datetimes it encounters in the file schema - it uses the pandas.to_datetime() function without the possibility of coercion for bad date times, this in turn must somehow be handling different bad cases differently as above.

**Comment by danlewis85** [comment]
I've raised this to see if there's any interest at: https://github.com/geopandas/geopandas/issues/2502

**Comment by jamesgyoung** [comment]
```python
df[k] = pd.to_datetime(df[k], errors="ignore").dt.round(freq="ms")
```
Is the fix looking at [these lines from geopandas code](https://github.com/geopandas/geopandas/blob/5c8ae832e030228b5deec02588c4e1b78dee0f18/geopandas/io/file.py#L343-L347) that appear to handle datetime columns.

**Comment by danlewis85** [comment]
This has been fixed in future versions of geopandas, relevant info is via https://github.com/geopandas/geopandas/issues/2502
