### ISSUE TITLE
Allow function caller to pass user defined schema

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#60]
In #52, @JamesKeny0n and @jpd-defra add a function called `_get_schema` that adds a dictionary, which maps column names to `numpy` data types, to a `VectorLayer` or `TiledVectorLayer` as a instance variable. (You'll probably need to branch off their branch if it hasn't be merged into `develop` before you start working on this issue).

See [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/e76ca05b4c6b7d760cd5dc9fc473cfacfa4e5aec/src/sds_data_model/_vector.py#L178-L190) for the function and [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/e76ca05b4c6b7d760cd5dc9fc473cfacfa4e5aec/src/sds_data_model/vector.py#L189) and [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/e76ca05b4c6b7d760cd5dc9fc473cfacfa4e5aec/src/sds_data_model/vector.py#L342) for how it's called when constructing a `VectorLayer` or `TiledVectorLayer`.

However, as @JamesKeny0n has pointed out [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/issues/40#issuecomment-1185889921), there are reasons why the data types returned by GDAL can't be trusted.

One solution to this problem is to hand responsibility for data types back to the function called. Therefore, I want you to add an optional parameter to the `from_files` method of  `VectorLayer` or `TiledVectorLayer` that takes a dictionary in the same format as the one returned by the `_get_schema` method. If such a dictionary is passed to the method, I want it to use that instead of calling `_get_schema`.

**Comment by JordanPinder-Defra** [comment]
@EFT-Defra is there any background information that accompanies this issue? Bit out the loop on what the task is specifically requiring so a quick breakdown might be useful.

**Comment by EFT-Defra** [comment]
Hi @JordanPinder-Defra, I've added some detail to the ticket, Does this help?

**Comment by JordanPinder-Defra** [comment]
@EFT-Defra absolutely, thank you!
