### ISSUE TITLE
Review metadata tasks

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#61]

**Comment by jpd-defra** [comment]
My [review](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/46#pullrequestreview-1047571449) here. Minor revisions requested and set as a new [ticket](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/issues/63).
