### ISSUE TITLE
Minor Revisions for metadata tasks PR

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#63]
Review is [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/46#pullrequestreview-1047571449).

**Comment by PiumiA** [comment]
I have removed myself from the assignee due to the questions raised are regarding Ed's work on Metadata.

**Comment by EFT-Defra** [comment]
I believe I have addressed @jpd-defra's concerns and have re-requested review.
