### ISSUE TITLE
Combine notes, diagrams, and previous writing into a single document

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#76]

**Comment by jpd-defra** [comment]
@s-flint-defra 

This came up in conversation between @EFT-Defra and I....

**What to do when a reviewer throws up something beyond the scope of the PR they are reviewing?** 

This happened when I was reviewing some changes Ed had made to the data model code. Initially my queries/thoughts were documented as a comment in the review at a relevant line number. Ed then created a new draft issue, re-using the text from the comment and providing a link back to the relevant part of the PR. Example [here](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/79#discussion_r937580562).

This allows us to continue with the review process while documenting this potential code ammendment in a separate package of work. 

We suggest that this might be a good way to handle such a situation, but also happy for you to build on/suggest an alternative!

**Comment by s-flint-defra** [comment]
Notes compiled and harmonised into a single document, comments welcomed.

https://defra.sharepoint.com/sites/MST-Defra-EAU-Spatial-Data-Science/Shared%20Documents/Data%20Cube/GitHub%20ways%20of%20working.docx?web=1
