### ISSUE TITLE
Ability to read a dataset partitioned across multiple files into a "single" spatially distributed object

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#77]
The `from_files` methods of `VectorLayer` and `TiledVectorLayer` only allow the caller to read data from a single vector file. However, some of the datasets we use are partitioned across multiple files. For example, the [Priority Habitat Inventory](https://www.data.gov.uk/dataset/4b6ddab7-6c0f-4407-946e-d6499f19fcde/priority-habitat-inventory-england) is split across three files: [North](https://naturalengland-defra.opendata.arcgis.com/datasets/Defra::priority-habitat-inventory-north-england/about), [Central](https://naturalengland-defra.opendata.arcgis.com/datasets/Defra::priority-habitat-inventory-central-england/about), and [South](https://naturalengland-defra.opendata.arcgis.com/datasets/Defra::priority-habitat-inventory-south-england/about), whereas, the [National Polygon dataset](https://use-land-property-data.service.gov.uk/datasets/nps#polygon) is split across 10 shapefiles. In these cases, we want to be able to read multiple vector files into a single `TiledVectorLayer`.

One option to explore is the [OGR Virtual Format](https://gdal.org/drivers/vector/vrt.html), specifically the [OGRVRTUnionLayer element](https://gdal.org/drivers/vector/vrt.html#ogrvrtunionlayer-element). This is an XML file, see example [here](https://gdal.org/drivers/vector/vrt.html#example-union-layer), which allows layers from multiple vector files to be read as a single layer. Though the GDAL documentation says that these XML files are normally prepared by hand, but you can use the GDAL command line utility [`ogrmerge`](https://gdal.org/programs/ogrmerge.html#ogrmerge) to generate them programmatically (@jpd-defra used this recently to merge the National Polygon dataset for 30 by 30). Since GDAL 3.2, many of the GDAL command line utilities have actually been available as functions that can be called within scripts and you can import `ogrmerge` as follows:

```python
from osgeo_utils.ogrmerge import ogrmerge
```

So, the idea is that it would be possible to pass a folder to the `data_path` argument of the `from_files` methods (possibly with a pattern as we did in the [`_get_paths`](https://github.com/Defra-Data-Science-Centre-of-Excellence/pyspark-vector-files/blob/6dd5483ab1441d9288e6d2e3bb660ff0140f7bdb/src/pyspark_vector_files/_files.py#L21-L44) in `pyspark-vector-files`) and then generate a VRT file from those files.

If [`pyogrio.read_dataframe`](https://pyogrio.readthedocs.io/en/latest/api.html#pyogrio.read_dataframe) can read VRT files, then we then read that into a `TiledVectorLayer`. If it can't, we need another solution...

**Comment by PiumiA** [comment]
To read a partitioned dataset into one single `TiledVectorLayer`, I have experimented using the OGR VRT format and `ogrmerge` function. The OGR VRT driver Union Layer can theoretically union a partitioned dataset by the creation of a vrt file written in xml. I first tried creating the vrt file using `ogrmerge`. This function returned a combined dataset of the file format. This meant that when I read in the 3 datasets of the Priority Habitats as shapefiles, a merged shapefile was created. This did not return a vrt file. Also, I was only successful in creating a merged file within the SCE but failed within a databricks notebook though I used the same files. Within the GDAL documentation, it mentions that using GDAL a vrt file format can be created using the `create()` function within . However, while trying to attempt this, I found that this only applied for vrt file creation for raster files and not for vector files. This meant that, I had to create a vrt file manually. The resultant vrt file was not able to be read in to `pyogrio.read_dataframe`.  I am not sure what other ways to approach this.
