### ISSUE TITLE
Implement aspatial data class

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#9]
We need class to represent aspatial data so that all data transformations can be captured within the data model.

To successfully complete this epic, you will need to demonstrate the following:

- Read in some aspatial, tabular dataset (e.g. a look up table) and some spatial dataset
- Filter or mutate the aspatial data in some way
- Join the two datasets
- Rasterise the combined dataset using an attribute from the aspatial dataset (to avoid depending on #4, this will have to be an attribute that can be represented by a `unit8`)

For example, you could refactor [this script](https://github.com/Defra-Data-Science-Centre-of-Excellence/30-by-30-Analysis/blob/main/Notebooks/rasterize_land_cover.py) to use your new class instead of using a DataFrame directly.

**Comment by EFT-Defra** [comment]
Like the `VectorLayer` and `TiledVectorLayer` classes, this class should contain `name`, `data`, and `metadata` attributes. The metadata attribute could be optional. For example:

```python
@dataclass
class AspatialData:
    name: str
    data: DataFrame
    metadata: Optional[Dict[str, Any]]
```

**Comment by EFT-Defra** [comment]
Also like those vector classes, it will also need to have a `from_files` [alternative constructor](https://docs.python.org/3/library/functions.html#classmethod) that will allow the caller to create it from a name and paths to the data and metadata files.

**Comment by EFT-Defra** [comment]
Ideally, we will be reading and writing tabular data in [the CSV-W format](https://www.gov.uk/government/publications/recommended-open-standards-for-government/using-metadata-to-describe-csv-data)

**Comment by EFT-Defra** [comment]
Like the `VectorTile` and `TiledVectorLayer` classes, we should be able to filter the data (by selecting columns or rows that meet arbitrary criteria), join it other data (spatial or aspatial), and derive new columns. This will require wrappers around the corresponding `pandas` functions. 

I might be worth seeing if we can cannibalise any of the [arrow-like filter functions](https://github.com/Defra-Data-Science-Centre-of-Excellence/esa_geo_utils/pull/1) @danlewis85 wrote to filter datasets opened with `fiona`.

**Comment by EFT-Defra** [comment]
As there will be lots of common functionality between the `VectorLayer`, `TiledVectorLayer`, and aspatial data classes, it might be worth defining that shared behaviour in an [Abstract Base Class](https://docs.python.org/3/library/abc.html) and then inheriting from that.

**Comment by danlewis85** [comment]
Here is the filtering code I wrote previously: [pyarrow-like code for fiona](https://github.com/Defra-Data-Science-Centre-of-Excellence/esa_geo_utils/blob/dev/dan/src/esa_geo_utils/io/fiona_filter.py)

**Comment by danlewis85** [comment]
> Like the `VectorTile` and `TiledVectorLayer` classes, we should be able to filter the data (by selecting columns or rows that meet arbitrary criteria), join it other data (spatial or aspatial), and derive new columns. This will require wrappers around the corresponding `pandas` functions.
> 
> I might be worth seeing if we can cannibalise any of the [arrow-like filter functions](https://github.com/Defra-Data-Science-Centre-of-Excellence/esa_geo_utils/pull/1) @danlewis85 wrote to filter datasets opened with `fiona`.

Having had a look at the code, I think that we'll simply be able to reuse the `_select`, `_where`, and `_join` functions in `_vector.py` as the geopandas and pandas versions of these are essentially the same. I do think we should move the code to using the `.loc[]` indexing operator though to avoid possible 'setting with copy' issues.

**Comment by danlewis85** [comment]
> Ideally, we will be reading and writing tabular data in [the CSV-W format](https://www.gov.uk/government/publications/recommended-open-standards-for-government/using-metadata-to-describe-csv-data)

Let's have a look at [csvcubed](https://digitalblog.ons.gov.uk/2022/05/24/csvcubed-a-new-tool-for-creating-csvws/) for this.

**Comment by danlewis85** [comment]
Do we want an option to read/write parquet?
