### ISSUE TITLE
Rasterization (to_raster) no handling no data correctly

### ISSUE THREAD

**Issue by s-flint-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#93]
@jpd-defra has noticed in testing the package that no data is not being handled correctly. I think this is because the method currently doesn't use the inherent pandas category lookup (because we generally cant read the whole dataset into memory). I wonder if we include a fill argument in rasterise as say '-1' as the dictionaries are enumerated from 0. Should work short term but there will be a more elegant solution.

**Comment by jpd-defra** [comment]
Thanks Sam for quickly whipping up a branch for me to try this. I can confirm that it does work. Things to consider for a future implementation:

- binary masks created with the data model currently produce 1s and 0s, so it creates an inconsistency where nodata is -1 in some datasets and 0 in others
- am I right in thinking adding -1 into the mix will up the minimum datatype, and potentially make the resultant zarr files bigger than neccessary? I think @JamesKeny0n and I were discussing this during the get data types sprint task.

**Comment by s-flint-defra** [comment]
Thanks for highlighting, yes both these things need considering. Could we somehow include the nodata value in the category lookup? 
A neater implementation that could happen with a little more time might:
- Allow the user to specify a nodata value (would need somehow to make sure that the user specified value is then subsequently used in the lookup creation, although if fill value is specified after the lookup creation some error raising could handle this).
- Set the fill value default to -1 or some other agreed value.
- I suspect you may be right that there will e implications for file size, but I am not sure of the magnitude. It may be that the increase is negligible relatively speaking
OR:
- Amend category lookup to bump all the values by 1 (effectively make it one-indexed).
- Use zero as the agreed nodata value.
- We may need to consider what this means for other types of layers where a zero might be meaningful. Perhaps writing a nodata dictionary to the attribute info in xarray could work across possible data types we handle, but different nodata values could be confusing for the user.

**Comment by EFT-Defra** [comment]
```python
@delayed
def _to_raster(
    gpdf: GeoDataFrame,
    column: str,
    out_shape: Tuple[int, int],
    dtype: str,
    transform: Affine,
    **kwargs,
) -> Delayed:
    """Returns a delayed boolean Numpy ndarray with values taken from a given column."""
    if all(gpdf.geometry.is_empty):
        # Return an array of -1 if the GeoDataFrame is empty, i.e. "No data"
        return full(
            shape=out_shape,
            fill_value=-1,
            dtype=dtype,
        )
    shapes = _get_shapes(
        gpdf=gpdf,
        column=column,
    )
    # Rasterise `int8` as `int16` then immediately downcast 
    if dtype == "int8":
        return rasterize(
            shapes=shapes,
            out_shape=out_shape,
            fill=-1,
            transform=transform,
            dtype="int16",
            **kwargs,
        ).astype("int8")
    return rasterize(
        shapes=shapes,
        out_shape=out_shape,
        fill=-1,
        transform=transform,
        dtype=dtype,
        **kwargs,
    )
```

**Comment by EFT-Defra** [comment]
Add "No Data" to `category_lookup`:

```python
def _get_category_lookup(
    categorical_column: Series,
) -> CategoryLookup:
    category_lookup = {
        index: category
        for index, category in enumerate(categorical_column.cat.categories)
    }
    category_lookup.update({-1: "No data"})
    return category_lookup
```

**Comment by EFT-Defra** [comment]
No need to upcast `int8` anymore

```python
def _get_category_dtype(
    categorical_column: Series,
) -> str:
    return categorical_column.cat.codes.dtype
```

**Comment by EFT-Defra** [comment]
Convert `None` to "No data":

```python
def _get_index_of_category(
    category_lookup: CategoryLookup,
    category: Optional[str],
) -> int:
    _category = category if category else "No data"
    return list(category_lookup.values()).index(_category)
```

**Comment by EFT-Defra** [comment]
I believe this works:

```python
@fixture
def gpdf() -> GeoDataFrame:
    return GeoDataFrame(
        data={
            "category": ["A", "B", "C", None],
            "geometry": [box(*bbox) for bbox in BBOXES[0:4]],
        },
        crs="EPSG:27700",
    )


@fixture
def expected_HL_array() -> NDArray[int8]:
    """The expected array for grid cell HL."""
    return zeros(
        shape=(10_000, 10_000),
        dtype=dtype("int8"),
    )

@fixture
def expected_HM_array() -> NDArray[int8]:
    """The expected array for grid cell HM."""
    return ones(
        shape=(10_000, 10_000),
        dtype=dtype("int8"),
    )


@fixture
def gpkg_path(tmp_path) -> Path:
    return tmp_path / "test.gpkg"


@fixture
def zarr_path(tmp_path) -> Path:
    return tmp_path / "test.zarr"


def test_pipeline(
    gpdf: GeoDataFrame,
    gpkg_path: Path,
    zarr_path: Path,
    expected_HL_array: NDArray[int8],
    expected_HM_array: NDArray[int8],
) -> None:
    gpdf.to_file(gpkg_path)

    pipeline = (
        VectorLayer.from_files(
            data_path=gpkg_path,
            name="test",
            convert_to_categorical=["category"],
        )
        .to_tiles()
        .to_dataset_as_raster(columns=["category"])
        .to_zarr(store=zarr_path, mode="w", compute=False,)
    )
    with ProgressBar():
        pipeline.compute()

    dataset = open_dataset(
        zarr_path,
        chunks={"northings": 10_000, "eastings": 10_000,},
        engine="zarr",
    )

    received_HL_array = dataset["category"][range(0, 10_000), range(0, 10_000)].values

    assert array_equal(
        a1=received_HL_array,
        a2=expected_HL_array,
    )

    received_HM_array = dataset["category"][range(0, 10_000), range(10_000, 20_000)].values

    assert array_equal(
        a1=received_HM_array,
        a2=expected_HM_array,
    )
```
